### ISSUE TITLE
✨ Counting overvotes

### ISSUE THREAD

**Issue by john-s-morgan** [microsoft/electionguard-core2#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

We need to add an overvote field to the contest that can hold the number of overvotes (0 or 1) that then can be encrypted like any other vote.  This way the normal adding of votes together process can be used to add the number of overvotes together to keep track of them.  From this, the overvote for the contest in the tally can then be decrypted like a vote count is to determine how many overvotes there were.  This number can then be used to display the overvotes.

**Comment by colleenirt** [comment]
this won't be done in this version
